add redpanda.yaml

diff --git a/.github/workflows/build-config.yml b/.github/workflows/build-config.yml
--- a/.github/workflows/build-config.yml
+++ b/.github/workflows/build-config.yml
@@ -1,52 +1,67 @@
 name: Build and test SQRL with Maven
 on:
   pull_request:
-    branches: [ "main", "v0.5.10-release"]
+    branches: ["main", "v0.5.10-release"]
 
 jobs:
   build:
     runs-on: ubuntu-latest
     timeout-minutes: 30
     env:
-      TZ: 'America/Los_Angeles'
+      TZ: "America/Los_Angeles"
     steps:
-    - name: Setup Timezone
-      uses: szenius/set-timezone@v1.1
-      with:
-        timezoneLinux: "America/Los_Angeles"
-    - name: checkout
-      uses: actions/checkout@v3
-    - name: Set up JDK 11
-      uses: actions/setup-java@v3
-      with:
-        java-version: '11'
-        distribution: 'adopt'
-        cache: maven
-    - name: Build SQRL
-      env:
-        DATASQRL_TOKEN: ${{ secrets.DATASQRL_TOKEN }}
-      run: mvn -T 1 -B -U -e clean verify
+      - name: Setup Timezone
+        uses: szenius/set-timezone@v1.1
+        with:
+          timezoneLinux: "America/Los_Angeles"
+      - name: checkout
+        uses: actions/checkout@v3
+      - name: Set up JDK 11
+        uses: actions/setup-java@v3
+        with:
+          java-version: "11"
+          distribution: "adopt"
+          cache: maven
+      - name: Build SQRL
+        env:
+          DATASQRL_TOKEN: ${{ secrets.DATASQRL_TOKEN }}
+        run: mvn -T 1 -B -U -e clean verify
 
-    - name: Build Docker image
-      run: docker build -t sqrl-test ./sqrl-tools
+      - name: Build Docker image
+        run: docker build -t sqrl-test ./sqrl-tools
 
-    - name: Run Docker container and execute tests
-      working-directory: ./sqrl-testing/sqrl-integration-tests/src/test/resources/usecases/conference
-      run: |
-        docker run -i --rm -v $PWD:/build sqrl-test test conference.sqrl conference.graphqls --snapshot snapshots-conference --tests tests-conference
-      continue-on-error: false
+      - name: Run Docker container and execute tests
+        working-directory: ./sqrl-testing/sqrl-integration-tests/src/test/resources/usecases/conference
+        run: |
+          docker run -i --rm -v $PWD:/build sqrl-test test conference.sqrl conference.graphqls --snapshot snapshots-conference --tests tests-conference
+        continue-on-error: false
 
-    - name: Test UDF
-      working-directory: ./sqrl-testing/sqrl-integration-tests/src/test/resources/usecases/udf
-      run: |
-        docker run -i --rm -v $PWD:/build sqrl-test test myudf.sqrl --snapshot snapshots-myudf --tests tests-myudf
-      continue-on-error: false
+      - name: Test UDF
+        working-directory: ./sqrl-testing/sqrl-integration-tests/src/test/resources/usecases/udf
+        run: |
+          docker run -i --rm -v $PWD:/build sqrl-test test myudf.sqrl --snapshot snapshots-myudf --tests tests-myudf
+        continue-on-error: false
 
-    - name: Check Docker return code
-      run: |
-        if [ $? -ne 0 ]; then
-          echo "Test failed."
-          exit 1
-        else
-          echo "Test passed."
-        fi
+      - name: Check Docker return code
+        run: |
+          if [ $? -ne 0 ]; then
+            echo "Test failed."
+            exit 1
+          else
+            echo "Test passed."
+          fi
+      - name: Set up Docker Buildx
+        uses: docker/setup-buildx-action@v2
+      - name: Login to Docker Hub
+        uses: docker/login-action@v2
+        with:
+          username: ${{ secrets.DOCKER_USERNAME }}
+          password: ${{ secrets.DOCKER_PASSWORD }}
+      - name: Build and Push sqrl-cli Dev
+        uses: docker/build-push-action@v3
+        with:
+          context: sqrl-tools
+          file: sqrl-tools/Dockerfile
+          push: true
+          tags: datasqrl/cmd:sqrltest
+          platforms: linux/amd64,linux/arm64
