Re-enable new run command (#838)
* Re-enable new run command

Signed-off-by: Daniel Henneberger <git@danielhenneberger.com>

* Reenable duckdb

Signed-off-by: Daniel Henneberger <git@danielhenneberger.com>

* Try duckdb

Signed-off-by: Daniel Henneberger <git@danielhenneberger.com>

* Disable test

Signed-off-by: Daniel Henneberger <git@danielhenneberger.com>

* Bump sensors timeout

Signed-off-by: Daniel Henneberger <git@danielhenneberger.com>

* Fix snap

Signed-off-by: Daniel Henneberger <git@danielhenneberger.com>

* Disable duckdb

Signed-off-by: Daniel Henneberger <git@danielhenneberger.com>

* renamed test case to make it less confusing

Signed-off-by: Matthias Broecheler <mbroecheler@users.noreply.github.com>

* Add sqrl test to build, clean up and unify

Signed-off-by: Daniel Henneberger <git@danielhenneberger.com>

* Fix path

Signed-off-by: Daniel Henneberger <git@danielhenneberger.com>

* Skip tests to test docker

Signed-off-by: Daniel Henneberger <git@danielhenneberger.com>

* Re-enable tests

Signed-off-by: Daniel Henneberger <git@danielhenneberger.com>

---------

Signed-off-by: Daniel Henneberger <git@danielhenneberger.com>
Signed-off-by: Matthias Broecheler <mbroecheler@users.noreply.github.com>
Co-authored-by: Matthias Broecheler <mbroecheler@users.noreply.github.com>

diff --git a/.github/workflows/build-config.yml b/.github/workflows/build-config.yml
--- a/.github/workflows/build-config.yml
+++ b/.github/workflows/build-config.yml
@@ -26,7 +26,21 @@ jobs:
       env:
         DATASQRL_TOKEN: ${{ secrets.DATASQRL_TOKEN }}
       run: mvn -T 1 -B -U -e clean verify
-#    - name: Build SQRL
-#      env:
-#        DATASQRL_TOKEN: ${{ secrets.DATASQRL_TOKEN }}
-#      run: mvn -T 1 -B -U -e clean verify -Dskip.unit.tests=true
+
+    - name: Build Docker image
+      run: docker build -t sqrl-test ./sqrl-tools
+
+    - name: Run Docker container and execute tests
+      working-directory: ./sqrl-testing/sqrl-integration-tests/src/test/resources/usecases/conference
+      run: |
+        docker run -i -p 8888:8888 -p 8081:8081 --rm -v $PWD:/build sqrl-test test conference.sqrl conference.graphqls
+      continue-on-error: false
+
+    - name: Check Docker return code
+      run: |
+        if [ $? -ne 0 ]; then
+          echo "Test failed."
+          exit 1
+        else
+          echo "Test passed."
+        fi
